---
title: "Fig.1"
author: "Marcin Sajek"
date: "6/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading_libraries, echo= FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyverse)
library(magrittr)
library(data.table)
library(Biostrings)
library(FcircSEC)
library(ggvenn)
library(ggpubr)
library(here)
```

merging all CIRI files

```{r merging_files, warning=FALSE, message=FALSE}
all_circs <- do.call(rbind,
          lapply(list.files(path = here('ciri_res'), pattern = 'circ.txt$', full.names = T), fread)) %>%
  dplyr::select(c(1:4,9:11)) %>%
  distinct(circRNA_ID, .keep_all = T)

fwrite(all_circs, here('circs_list','all_hb_and_GBM_circs.tsv'), sep = '\t')

all_circs %>% 
  dplyr::select(2:4,7) %>%
  fwrite(here('circ_seqs', 'GBM_and_brain_all.bed'), sep = '\t', col.names = F)

hb_circs <- do.call(rbind,
          lapply(list.files(path = here('ciri_res'), pattern = 'circ.txt$', full.names = T)[1:18], fread)) %>%
  dplyr::select(c(1:4,9)) %>%
  distinct(circRNA_ID, .keep_all = T) %>%
  mutate(dataset = 'healthy brain control')

fwrite(hb_circs, here('circs_list','healthy_brain_circs.tsv'), sep = '\t')

gbm_prim_circs <- do.call(rbind,
          lapply(list.files(path = here('ciri_res'), pattern = 'circ.txt$', full.names = T)[19:41], fread)) %>%
  dplyr::select(c(1:4,9)) %>%
  distinct(circRNA_ID, .keep_all = T) %>%
  mutate(dataset = 'GBM primary')

fwrite(gbm_prim_circs, here('circs_list','GBM_prim_circs.tsv'), sep = '\t')

gbm_rec_circs <- do.call(rbind,
          lapply(list.files(path = here('ciri_res'), pattern = 'circ.txt$', full.names = T)[42:44], fread)) %>%
  dplyr::select(c(1:4,9)) %>%
  distinct(circRNA_ID, .keep_all = T) %>%
  mutate(dataset = 'GBM recurrent')

fwrite(gbm_rec_circs, here('circs_list','GBM_rec_circs.tsv'), sep = '\t')
```

extracting circRNA sequences (FCircSEC can be written in slightly more convenient way)

```{r extract_seqs, warning=FALSE, message=FALSE}
system('wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_30/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz')
system('wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_30/GRCh37_mapping/gencode_v30lift37.gtf.gz')
system('pigz -d *.gz')
system(paste0('mv ',here(),'/GRCh37.primary_assembly.genome.fa ',here(),'/gencode_v30lift37.gtf ',here(), '/circ_seqs'))

#transcriptExtract(here('circ_seqs','gencode_v30lift37.gtf'), 'other', 'transcriptdata.txt') # run this line only once, it takes long time
#fread(here('circ_seqs','transcriptdata.txt')) %>%
  #fwrite(here('circ_seqs','transcript_data.txt'), sep = '\t', quote = T)
fread(here('circ_seqs', 'GBM_and_brain_all.bed')) %>%
  fwrite(here('circ_seqs','GBM_and_brain_all_quoted.bed'), sep = '\t', quote = T, col.names = F)
circClassification(here('circ_seqs','transcript_data.txt'), here('circ_seqs','GBM_and_brain_all_quoted.bed'),here('circ_seqs','GBM_and_brain_all_class.txt'), here('circ_seqs','GBM_and_brain_all_class.bed'))      
get.fasta(here('circ_seqs','GRCh37.primary_assembly.genome.fa'), here('circ_seqs','GBM_and_brain_all_class.bed'), here('circ_seqs','GBM_and_brain_all_genomic_seq.fa'))
circSeqExt(here('circ_seqs','GBM_and_brain_all_genomic_seq.fa'), here('circ_seqs','GBM_and_brain_all_class.txt'), here('circ_seqs','GBM_and_brain_all.fa'))
```

circs annotation (Fig 1a-d)

```{r annotation, warning=FALSE, message=FALSE}
all_circs %>%
  mutate(ID = paste0(chr,':',circRNA_start -1,'-', circRNA_end)) %>%
  na.omit() %>%
  dplyr::select('ID') %>%
  fwrite(here('annotation','circMine_coords_GBM_and_brain.tsv'), sep = '\t')

circMine_annot <- fread(here('annotation', 'circMine_annot_hb_and_GBM.csv'))

all_circs_4annot <- all_circs %>%
  mutate(ID = paste0(chr,':',circRNA_start -1,'-', circRNA_end),
         annotation = factor(if_else(ID%in%circMine_annot$Hg19, 'Annotated circRNAs','Novel circRNAs')))

pie_all <- ggplot(plyr::count(all_circs_4annot$annotation), aes(x = '', y = freq, fill = x)) +
  geom_col(color = 'black') +
  coord_polar(theta = 'y')+
  scale_fill_grey() +  
  theme_pubclean() +
  theme(axis.text.x=element_blank())+
  theme(axis.title.x=element_blank())+
  theme(axis.title.y=element_blank())+
  rremove('legend.title')

pdf(here('Fig1','1a.pdf'))
pie_all
dev.off()

hb_circs_4annot <- hb_circs %>%
  mutate(ID = paste0(chr,':',circRNA_start -1,'-', circRNA_end),
         annotation = factor(if_else(ID%in%circMine_annot$Hg19, 'Annotated circRNAs','Novel circRNAs')))

pie_hb <- ggplot(plyr::count(hb_circs_4annot$annotation), aes(x = '', y = freq, fill = x)) +
  geom_col(color = 'black') +
  coord_polar(theta = 'y')+
  scale_fill_grey() +  
  theme_pubclean() +
  theme(axis.text.x=element_blank())+
  theme(axis.title.x=element_blank())+
  theme(axis.title.y=element_blank())+
  rremove('legend.title')

pdf(here('Fig1','1b.pdf'))
pie_hb
dev.off()

prim_circs_4annot <- gbm_prim_circs %>%
  mutate(ID = paste0(chr,':',circRNA_start -1,'-', circRNA_end),
         annotation = factor(if_else(ID%in%circMine_annot$Hg19, 'Annotated circRNAs','Novel circRNAs')))

pie_prim <- ggplot(plyr::count(prim_circs_4annot$annotation), aes(x = '', y = freq, fill = x)) +
  geom_col(color = 'black') +
  coord_polar(theta = 'y')+
  scale_fill_grey() +  
  theme_pubclean() +
  theme(axis.text.x=element_blank())+
  theme(axis.title.x=element_blank())+
  theme(axis.title.y=element_blank())+
  rremove('legend.title')

pdf(here('Fig1','1c.pdf'))
pie_prim
dev.off()

rec_circs_4annot <- gbm_rec_circs %>%
  mutate(ID = paste0(chr,':',circRNA_start -1,'-', circRNA_end),
         annotation = factor(if_else(ID%in%circMine_annot$Hg19, 'Annotated circRNAs','Novel circRNAs')))

pie_rec <- ggplot(plyr::count(rec_circs_4annot$annotation), aes(x = '', y = freq, fill = x)) +
  geom_col(color = 'black') +
  coord_polar(theta = 'y')+
  scale_fill_grey() +  
  theme_pubclean() +
  theme(axis.text.x=element_blank())+
  theme(axis.title.x=element_blank())+
  theme(axis.title.y=element_blank())+
  rremove('legend.title')

pdf(here('Fig1','1d.pdf'))
pie_rec
dev.off()
```

venn diagram (Fig 1e)

```{r venn, warning=FALSE, message=FALSE}
venn_diag <- ggvenn(data = list(GBM_primary = gbm_prim_circs$circRNA_ID, GBM_recurrent = gbm_rec_circs$circRNA_ID, Healthy_brain = hb_circs$circRNA_ID),
                    show_percentage = F)
pdf(here('Fig1','1e.pdf'))
venn_diag
dev.off()
```

bar plot circ types (Fig 1f)

```{r circ_types, warning=FALSE, message=FALSE}
circ_types_df <- rbind(hb_circs, gbm_prim_circs, gbm_rec_circs) %>%
  mutate(dataset = factor(dataset, levels = c('healthy brain control','GBM primary','GBM recurrent')),
         circRNA_type = factor(circRNA_type, levels = c('exon','intron','intergenic_region')))

bar_plt <- ggplot(data = circ_types_df, aes(x = dataset, color = circRNA_type, fill = circRNA_type))+
  geom_bar(stat="count", width=0.8)+
  labs(y="Number of circRNA")+
  theme_bw()+
  theme(axis.text.x=element_text(size=16)) +
  theme(axis.text.y=element_text(size=16)) +
  theme(axis.text.x=element_text(size=16, angle = 45, vjust = 1, hjust = 1)) +
  theme(axis.title.y=element_text(size=20)) +
  theme(legend.text=element_text(size=18)) +
  theme(legend.title=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 3)))+
  rremove('xlab')

pdf((here('Fig1','1f.pdf')))
bar_plt
dev.off()
```

length (Fig 1g-i)

```{r length, warning=FALSE, message=FALSE}
all_circs_length <- readDNAStringSet(here('circ_seqs','GBM_and_brain_all.fa')) %>%
  lapply(., length) %>%
  unlist() %>%
  enframe() %>%
  dplyr::rename(c('ID'='name','length'='value')) %>%
  mutate(ID = gsub('-','|',ID))
hb_len <- all_circs_length %>%
  filter(ID%in%hb_circs$circRNA_ID)
prim_len <- all_circs_length %>%
  filter(ID%in%gbm_prim_circs$circRNA_ID)
rec_len <- all_circs_length %>%
  filter(ID%in%gbm_rec_circs$circRNA_ID)

hb_len_hist <- ggplot(data = hb_len, aes(x = length))+
  geom_histogram(binwidth = 50, 
                 col="black", 
                 fill="blue", 
                 alpha = .2)+ 
  ggtitle("healthy brain control")+
  labs(x="Spliced length", y="Number of circRNA")+
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size = 20))+
  theme(axis.text.x=element_text(size=16)) +
  theme(axis.text.y=element_text(size=16)) +
  theme(axis.title.x=element_text(size=20)) +
  theme(axis.title.y=element_text(size=20)) +
  coord_cartesian(xlim=c(1,5000))+
  geom_vline(xintercept = median(hb_len$length),
             col = "red",
             lwd = .2,
             linetype = 'dashed')

prim_len_hist <- ggplot(data = prim_len, aes(x = length))+
  geom_histogram(binwidth = 50, 
                 col="black", 
                 fill="blue", 
                 alpha = .2)+ 
  ggtitle("GBM primary")+
  labs(x="Spliced length", y="Number of circRNA")+
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size = 20))+
  theme(axis.text.x=element_text(size=16)) +
  theme(axis.text.y=element_text(size=16)) +
  theme(axis.title.x=element_text(size=20)) +
  theme(axis.title.y=element_text(size=20)) +
  coord_cartesian(xlim=c(1,5000))+
  geom_vline(xintercept = median(prim_len$length),
             col = "red",
             lwd = .2,
             linetype = 'dashed')

rec_len_hist <- ggplot(data = rec_len, aes(x = length))+
  geom_histogram(binwidth = 50, 
                 col="black", 
                 fill="blue", 
                 alpha = .2)+ 
  ggtitle("GBM recurrent")+
  labs(x="Spliced length", y="Number of circRNA")+
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5, size = 20))+
  theme(axis.text.x=element_text(size=16)) +
  theme(axis.text.y=element_text(size=16)) +
  theme(axis.title.x=element_text(size=20)) +
  theme(axis.title.y=element_text(size=20)) +
  coord_cartesian(xlim=c(1,5000))+
  geom_vline(xintercept = median(rec_len$length),
             col = "red",
             lwd = .2,
             linetype = 'dashed')

pdf((here('Fig1','1g.pdf')))
hb_len_hist
dev.off()

pdf((here('Fig1','1h.pdf')))
prim_len_hist
dev.off()

pdf((here('Fig1','1i.pdf')))
rec_len_hist
dev.off()
```

circRNA on chromosomes (suppl fig)

```{r chrom, warning=FALSE, message=FALSE}
chrom_cnt_table <- rbind(hb_circs, gbm_prim_circs, gbm_rec_circs) %>%
  mutate(chr = factor(if_else(nchar(chr) == 4 & !chr == 'chrX' & !chr == 'chrY', gsub('chr','chr0',chr), chr)),
         grouping_var = paste0(chr,'_',dataset),
         dataset = factor(dataset, levels = c('healthy brain control', 'GBM primary', 'GBM recurrent'))) %>%
  group_by(grouping_var) %>%
  mutate(chr_counts = n()) %>%
  distinct(grouping_var, .keep_all = T) %>%
  ungroup() %>%
  group_by(dataset) %>%
  mutate(chr_perc = chr_counts/sum(chr_counts))

chr_bar_plt <- ggbarplot(chrom_cnt_table, x = 'chr', y = 'chr_perc',
                         col='black', fill='blue', alpha = .2,
                         facet.by = 'dataset')+ 
  scale_y_continuous(labels = scales::percent)+
  theme_bw()+
  rremove('xlab')+
  rremove('ylab')+
  theme(axis.text.x=element_text(size=14,angle = 90, vjust = 0.5, hjust=1)) +
  theme(axis.text.y=element_text(size=16)) +
  theme(strip.text.x = element_text(size = 20))

pdf(here('suppl_figs','chr_hb_and_gbm.pdf'), width = 12, height = 8)
chr_bar_plt
dev.off()
```